<a href="https://colab.research.google.com/github/amalvarezme/Python_Basics/blob/main/Others/Ejercicios_Funciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ejercicio_1

Dado un arreglo de enteros, escribe una función que calcule el número de secuencias continuas de al menos dos números iguales en el arreglo.


In [ ]:
import numpy as np

def num_secuencias_iguales(arr):
    # Usamos la función diff de numpy para obtener las diferencias entre elementos consecutivos
    diff_arr = np.diff(arr)
    # Buscamos los índices donde hay un cambio en la secuencia de números
    indices_cambio = np.where(diff_arr != 0)[0] + 1
    # Contamos la cantidad de secuencias de números iguales (con más de un elemento)
    num_secuencias = np.sum(indices_cambio - np.roll(indices_cambio, 1) > 1)
    return num_secuencias

###Funciones utilizadas

### 1) np.diff():

El comando 'np.diff()' calcula la diferencia entre elementos adyacentes a lo largo de un eje determinado de un arreglo NumPy. Por defecto, 'np.diff()' calcula la diferencia entre elementos adyacentes a lo largo del primer eje del arreglo.

Ejemplo:

In [ ]:
import numpy as np

a = np.array([1, 3, 6, 10])
diffs = np.diff(a)
print(diffs)

[2 3 4]


En este ejemplo, creamos un arreglo NumPy a con los valores [1, 3, 6, 10]. Luego, calculamos las diferencias entre elementos adyacentes de a utilizando el comando np.diff(). La variable diffs contiene las diferencias resultantes, que son [2, 3, 4]. La diferencia entre 3 y 1 es 2, la diferencia entre 6 y 3 es 3, y la diferencia entre 10 y 6 es 4.

### 2) np.where():

El comando 'np.where()' devuelve un arreglo NumPy que contiene elementos de uno de dos arreglos de entrada, dependiendo de una condición dada.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
cond = np.array([True, False, False, True])

result = np.where(cond, a, b)
print(result)



[ 1 20 30  4]


En este ejemplo, creamos dos arreglos NumPy a y b con los valores [1, 2, 3, 4] y [10, 20, 30, 40], respectivamente. Luego, creamos un arreglo booleano cond con los valores [True, False, True, False]. El comando np.where() devuelve un nuevo arreglo NumPy result, que contiene los elementos de a donde cond es True, y los elementos de b donde cond es False. En este caso, result es [1, 20, 3, 40].

### 3) np.sum:

El comando np.sum() calcula la suma de los elementos de un arreglo NumPy a lo largo de un eje determinado. Por defecto, np.sum() calcula la suma de todos los elementos del arreglo.

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
sum_total = np.sum(a)
sum_filas = np.sum(a, axis=0)
sum_columnas = np.sum(a, axis=1)

print(sum_total)
print(sum_filas)
print(sum_columnas)

10
[4 6]
[3 7]


En este ejemplo, creamos un arreglo NumPy a con los valores [[1, 2], [3, 4]]. Luego, utilizamos el comando np.sum() para calcular la suma de los elementos de a. La variable sum_total contiene la suma total, que es 10.

También podemos utilizar np.sum() para calcular la suma a lo largo de los ejes de a. En este caso, np.sum(a, axis=0) calcula la suma a lo largo del primer eje, que corresponde a la suma de las columnas de

## Ejercicio_2:Cálculo de la distancia entre dos puntos en un plano

En este ejercicio, se pide a los estudiantes que escriban una función que calcule la distancia entre dos puntos en un plano utilizando NumPy. La distancia entre dos puntos en un plano se puede calcular utilizando la fórmula:

$$d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$$

La función debe tomar las coordenadas de los dos puntos como argumentos y devolver la distancia entre ellos.





In [ ]:
import numpy as np

def distancia(punto1, punto2):
    x1, y1 = punto1
    x2, y2 = punto2
    distancia = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)
    return distancia

# Ejemplo de uso
punto1 = (1, 2)
punto2 = (4, 6)
resultado = distancia(punto1, punto2)
print(resultado)

5.0


### Funciones a utilizar:

#### 'np.sqrt':

Es una función en Python del paquete NumPy que se utiliza para calcular la raíz cuadrada de un número o una matriz de números.

Por ejemplo, si queremos calcular la raíz cuadrada de un número 9, podemos hacerlo de la siguiente manera:




In [ ]:
import numpy as np

x = 9
raiz_cuadrada = np.sqrt(x)
print(raiz_cuadrada)

3.0


Esto imprimirá el resultado de la raíz cuadrada de 9, que es 3.0.

También podemos utilizar np.sqrt para calcular la raíz cuadrada de una matriz de números, por ejemplo:



In [ ]:
import numpy as np

x = np.array([4, 9, 16])
raiz_cuadrada = np.sqrt(x)
print(raiz_cuadrada)

[2. 3. 4.]


## Ejercicio_3:

En este ejercicio, se le pide a los estudiantes que creen un vector numpy de 5 elementos aleatorios entre 0 y 1, y luego lo multipliquen por una matriz aleatoria de 5x5 también creada con la biblioteca random. Finalmente, deben imprimir la suma de las filas de la matriz resultante.

In [ ]:
import numpy as np
import random

# Creamos el vector aleatorio de 5 elementos
vector = np.random.rand(5)

# Creamos la matriz aleatoria de 5x5
matriz = np.random.rand(5,5)

# Multiplicamos el vector por la matriz
resultado = np.dot(vector, matriz)

# Sumamos las filas de la matriz resultante
suma_filas = np.sum(resultado, axis=1)

print("Vector aleatorio:", vector)
print("Matriz aleatoria:\n", matriz)
print("Resultado de la multiplicación:", resultado)
print("Suma de las filas de la matriz resultante:", suma_filas)

##Ejercicio_4:

En este ejercicio, se le pide a los estudiantes que creen una matriz numpy aleatoria de 3x3 con números enteros entre 1 y 10. Luego deben encontrar el valor máximo y mínimo de la matriz, y finalmente imprimir la matriz original con el valor máximo resaltado con una X y el valor mínimo resaltado con una O.

In [ ]:
import numpy as np
import random

# Creamos la matriz aleatoria de 3x3 con enteros entre 1 y 10
matriz = np.random.randint(1, 11, size=(3,3))

# Encontramos el valor máximo y mínimo de la matriz
maximo = np.max(matriz)
minimo = np.min(matriz)

# Iteramos sobre cada elemento de la matriz y creamos una nueva matriz con
# cada valor resaltado en "X" si es el máximo, en "O" si es el mínimo, y en
# el valor original en cualquier otro caso

matriz_resaltada = np.zeros_like(matriz, dtype=str)                             #Devuelve una matriz de cero identica a la dimensión de la matriz y sus mismo tipos de datos

for i in range(matriz.shape[0]):
    for j in range(matriz.shape[1]):
        if matriz[i,j] == maximo:
            matriz_resaltada[i,j] = "X"
        elif matriz[i,j] == minimo:
            matriz_resaltada[i,j] = "O"
        else:
            matriz_resaltada[i,j] = str(matriz[i,j])

# Imprimimos la matriz original y la matriz resaltada
print("Matriz original:\n", matriz)
print("Matriz resaltada:\n", matriz_resaltada)

Matriz original:
 [[ 4  1  8]
 [ 4  6 10]
 [ 7 10  6]]
Matriz resaltada:
 [['4' 'O' '8']
 ['4' '6' 'X']
 ['7' 'X' '6']]


##Ejercicio_5:

- Crea una matriz aleatoria de 5x5 con enteros entre 1 y 20.
- Encuentra el valor máximo y mínimo de la matriz.
- Itera sobre cada elemento de la matriz y crea una nueva matriz con cada valor resaltado en "X" si es el máximo, en "O" si es el mínimo, y en el valor original en cualquier otro caso.
-Imprime la matriz original y la matriz resaltada.

In [ ]:
import numpy as np

# Creamos la matriz aleatoria de 5x5 con enteros entre 1 y 20
matriz = np.random.randint(1, 21, size=(5,5))

# Encontramos el valor máximo y mínimo de la matriz
maximo = np.max(matriz)
minimo = np.min(matriz)

# Iteramos sobre cada elemento de la matriz y creamos una nueva matriz con
# cada valor resaltado en "X" si es el máximo, en "O" si es el mínimo, y en
# el valor original en cualquier otro caso
matriz_resaltada = np.zeros_like(matriz, dtype=str)
for i in range(matriz.shape[0]):
    for j in range(matriz.shape[1]):
        if matriz[i,j] == maximo:
            matriz_resaltada[i,j] = "X"
        elif matriz[i,j] == minimo:
            matriz_resaltada[i,j] = "O"
        else:
            matriz_resaltada[i,j] = str(matriz[i,j])

# Imprimimos la matriz original y la matriz resaltada
print("Matriz original:\n", matriz)
print("Matriz resaltada:\n", matriz_resaltada)

Matriz original:
 [[ 7 10  6 10  5]
 [19 16 11 20 16]
 [10 19 11 11 15]
 [ 3 14 18 15 12]
 [ 6 14  3  7 18]]
Matriz resaltada:
 [['7' '1' '6' '1' '5']
 ['1' '1' '1' 'X' '1']
 ['1' '1' '1' '1' '1']
 ['O' '1' '1' '1' '1']
 ['6' '1' 'O' '7' '1']]


### Indicaciones para el parcial.

1. Si usan alguna función diferente a la que hemos visto en clase, debe ser documentada.

2. Los comentarios deben ser un 20% de inglés.

3. Puntualidad.

##Ejercicio_Parcial.

Crear juego de sudoku, SIN las reglas.


In [ ]:
import random

# Crear una lista vacía de 9x9 para el sudoku
sudoku = [[0 for x in range(9)] for y in range(9)]

# Rellenar el sudoku con números aleatorios del 1 al 9
for i in range(9):
    for j in range(9):
        sudoku[i][j] = random.randint(1, 9)

# Imprimir el sudoku
for i in range(9):
    for j in range(9):
        print(sudoku[i][j],end=" ")
        if j == 2 or j == 5:
            print("|",end=" ")
    print()
    if i == 2 or i == 5:
        print("-" * 22)

1 4 1 | 1 4 9 | 3 1 5 
3 5 5 | 7 7 2 | 4 7 8 
1 4 3 | 2 1 4 | 5 7 1 
----------------------
1 8 4 | 9 3 3 | 3 2 3 
6 7 6 | 1 9 1 | 3 5 5 
4 6 2 | 6 2 8 | 4 7 5 
----------------------
6 8 7 | 7 5 1 | 4 3 3 
3 8 3 | 3 8 3 | 5 2 8 
3 7 8 | 3 6 3 | 4 8 6 


In [ ]:
import random

def create_board():
    # Crea un tablero de sudoku aleatorio
    board = [[0 for x in range(9)] for y in range(9)]
    nums = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    # Rellena el tablero con números aleatorios
    for i in range(9):
        random.shuffle(nums)
        for j in range(9):
            board[i][j] = nums[j]
        nums = nums[3:] + nums[:3]
    return board

def print_board(board):
    # Imprime el tablero en la consola
    for i in range(9):
        if i % 3 == 0 and i != 0:
            print("- - - - - - - - - - - - ")
        for j in range(9):
            if j % 3 == 0 and j != 0:
                print(" | ", end="")
            if j == 8:
                print(board[i][j])
            else:
                print(str(board[i][j]) + " ", end="")

# Crear un tablero de sudoku
board = create_board()
# Imprimir el tablero
print_board(board)

7 4 3  | 5 8 9  | 1 2 6
9 4 1  | 8 5 7  | 2 6 3
4 2 9  | 6 7 8  | 3 1 5
- - - - - - - - - - - - 
7 3 6  | 5 2 9  | 1 8 4
2 6 9  | 8 4 7  | 1 3 5
7 8 9  | 5 1 6  | 2 4 3
- - - - - - - - - - - - 
3 6 4  | 2 5 9  | 1 7 8
5 6 2  | 9 7 1  | 4 8 3
1 4 2  | 9 3 6  | 7 5 8
